# Generated by Django 5.1.7 on 2025-03-24 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_company', models.CharField(max_length=50)),
                ('project_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('native_license_expiry', models.DateField(blank=True, null=True)),
                ('assigned_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('recruitment_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='dashboard.projectmaster')),
            ],
        ),
        migrations.CreateModel(
            name='NewHire',
            fields=[
                ('employee_id', models.IntegerField()),
                ('new_hire_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_company_name', models.CharField(max_length=100)),
                ('arrived_salary', models.DecimalField(decimal_places=2, max_digits=18)),
                ('native_language', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('food_type', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=400)),
                ('email_id', models.EmailField(max_length=50)),
                ('city_of_birth', models.CharField(max_length=50)),
                ('work_status', models.CharField(max_length=50)),
                ('remark', models.TextField()),
                ('camp_id', models.IntegerField()),
                ('employee_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
        ),
        migrations.CreateModel(
            name='JobMaster',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='dashboard.projectmaster')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('wo_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('days_taken', models.IntegerField(blank=True, null=True)),
                ('wo_description', models.TextField(blank=True, null=True)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='initiated', max_length=20)),
                ('status_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='dashboard.jobmaster')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='dashboard.projectmaster')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_work_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
