# Generated by Django 5.1.6 on 2025-03-06 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampMaster',
            fields=[
                ('CampId', models.AutoField(primary_key=True, serialize=False)),
                ('CampName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobMaster',
            fields=[
                ('JobId', models.AutoField(primary_key=True, serialize=False)),
                ('JobName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ManningReport',
            fields=[
                ('ManningReportId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=255)),
                ('OnGround', models.IntegerField()),
                ('Backfill', models.IntegerField()),
                ('Additional', models.IntegerField()),
                ('Vacancy', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('WorkOrderId', models.AutoField(primary_key=True, serialize=False)),
                ('OpenWorkOrders', models.IntegerField()),
                ('ClosedInSameDay', models.IntegerField()),
                ('ClosedInOneDay', models.IntegerField()),
                ('ClosedInTwoDay', models.IntegerField()),
                ('ClosedInThreeDay', models.IntegerField()),
                ('ClosedInFourDay', models.IntegerField()),
                ('ClosedInFiveDay', models.IntegerField()),
                ('ClosedInMoreThanFiveDay', models.IntegerField()),
                ('TotalWorkOrders', models.IntegerField()),
                ('CompletionRate', models.FloatField()),
                ('CampId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campmaster')),
            ],
        ),
    ]
